version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'asterisk'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'asterisk'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    image: teste10
    ports:
      - "5007:5007"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

# Names our volume
volumes:
  my-db: